"use client";

import { useState, useCallback, useEffect } from "react";
import { FileText, Copy, Check, Sparkles, Loader2 } from "lucide-react";
import { useLocalAI } from "@/hooks/useLocalAI";
import { PROMPTS } from "@/lib/ai/prompts";
import AIStreamOutput from "@/components/AIStreamOutput";
import AIChip from "@/components/AIChip";
import FeatureLock from "@/components/ai/FeatureLock";
import ToolPageHeader from "@/components/tools/ToolPageHeader";
import { trackEvent } from "@/lib/analytics";

export default function ContractAnalyzer() {
  const { isReady, isSupported, loadModel, streamInfer, status } = useLocalAI();
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    trackEvent("tool_opened", { tool: "contract_analyzer" });
  }, []);

  const handleAnalyze = useCallback(async () => {
    if (!input.trim()) return;

    if (!isReady) {
      await loadModel();
    }

    setOutput("");
    setIsStreaming(true);

    try {
      await streamInfer(
        `Analyze the following contract or legal agreement:\n\n${input}`,
        PROMPTS.contractAnalyzer,
        (token) => setOutput((prev) => prev + token),
      );
      trackEvent("ai_tool_used", { tool: "contract_analyzer" });
    } catch {
      setOutput("Error: Failed to analyze contract. Please try again.");
    } finally {
      setIsStreaming(false);
    }
  }, [input, isReady, loadModel, streamInfer]);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [output]);

  const isModelLoading = status === "downloading" || status === "loading";

  return (
    <div>
      <ToolPageHeader
        icon={FileText}
        title="Contract Analyzer"
        description="Paste a contract or legal agreement to get a clause-by-clause analysis with color-coded severity ratings."
      />

      <FeatureLock requiredCapability="contract_analyze">
        <div className="space-y-6">
          {/* Input */}
          <div>
            <label className="block text-sm font-medium text-text-secondary mb-2">
              Contract text
            </label>
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Paste the contract or legal agreement text here..."
              rows={10}
              className="w-full bg-bg-elevated border border-border rounded-xl px-4 py-3 text-sm text-text-primary placeholder:text-text-tertiary focus:outline-none focus:ring-2 focus:ring-accent/50 resize-y"
            />
            <p className="text-text-tertiary text-xs mt-1">
              {input.length.toLocaleString()} characters
            </p>
          </div>

          {/* Analyze button */}
          {!isSupported ? (
            <p className="text-text-tertiary text-sm">
              WebGPU required. Try Chrome or Edge, or install Ollama.
            </p>
          ) : (
            <button
              onClick={handleAnalyze}
              disabled={!input.trim() || isStreaming || isModelLoading}
              className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-accent hover:bg-accent/90 text-accent-fg rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isStreaming || isModelLoading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4" />
              )}
              {isModelLoading
                ? "Loading AI model..."
                : isStreaming
                  ? "Analyzing..."
                  : "Analyze Contract"}
            </button>
          )}

          {/* Output */}
          <AIStreamOutput content={output} isStreaming={isStreaming} />

          {/* Copy button */}
          {output && !isStreaming && (
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2 bg-bg-elevated hover:bg-bg-hover text-text-primary border border-border rounded-lg text-sm font-medium transition-colors"
            >
              {copied ? (
                <Check className="w-4 h-4 text-grade-a" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
              {copied ? "Copied" : "Copy to clipboard"}
            </button>
          )}

          {/* Legal disclaimer */}
          <div className="p-3 bg-bg-elevated border border-border rounded-lg">
            <p className="text-text-tertiary text-xs">
              This is not legal advice. Consult a qualified attorney for
              important decisions.
            </p>
          </div>

          <p className="text-text-tertiary text-xs mt-6">
            Generated by local AI — may contain errors.
          </p>
        </div>
      </FeatureLock>
    </div>
  );
}
